package com.moniewise.moniewise_backend.enums;

public enum NotificationType {
    MATURITY_ALERT,
    GRACE_PERIOD_REMINDER,
    EXPIRATION_NOTICE,
    BUDGET_COMPLETED,
    WELCOME,
    GENERAL,
    BUDGET_END,
    PRE_DISBURSEMENT,
    DISBURSEMENT,
    EXPIRED_DISBURSEMENT,
    ENVELOPE_TRANSFER,
    EXTERNAL_TRANSFER,
    INSUFFICIENT_BALANCE,
    BUDGET_CREATION_FEE,
    WALLET_FUNDED,

    BUDGET_CREATION



    }
