package com.moniewise.moniewise_backend.enums;

public enum NotificationType {
    MATURITY_ALERT,
    BUDGET_LIMIT_WARNING,
    BUDGET_COMPLETED,
    WELCOME,
    BUDGET_END,
    PRE_DISBURSEMENT,
    DISBURSEMENT,
    WITHDRAWAL,
    EXPIRED_DISBURSEMENT,
    ENVELOPE_TRANSFER,
    EXTERNAL_TRANSFER,
    INSUFFICIENT_BALANCE,
    BUDGET_CREATION_FEE,
    WALLET_FUNDED,
    BUDGET_CREATION,
    ENVELOPE_CREATED,
    ENVELOPE_UPDATED,
    ENVELOPE_DELETED,
    BUDGET_END_SOON,           // 3 days left
    DISBURSEMENT_SUCCESS,      // Money released
    DISBURSEMENT_FAILED,       // Grace period expired
    LIMIT_REACHED,             // Daily/weekly cap
    EMERGENCY_USED,
    WEEKLY_SUMMARY,
    POSITIVE_NUDGE,
    REFUND_ISSUED,
    BUDGET_EXPIRED,
    ENVELOPE_LOCKED,
    ENVELOPE_UNLOCKED,
    LOW_BALANCE_WARNING,
    GOAL_ACHIEVED,
    BUDGET_UPDATED,
    DISBURSEMENT_REMINDER,
    SYSTEM,
    BUDGET_CREATION_SUCCESS,
    WALLET_DEPOSIT,
    DISBURSEMENT_READY,
    BUDGET_ENDING_SOON,
    ENVELOPE_LOW_BALANCE,
    DISBURSEMENT_REFUNDED,
    BUDGET_UNALLOCATED_REFUNDED,
    SAVINGS_MATURED,
    SAVINGS_MATURING_SOON,     // 7 days left

    // ── Payeelord VAS (airtime & data) ──────────────────────────────────────
    AIRTIME_PURCHASE_SUCCESS,
    AIRTIME_PURCHASE_FAILED,
    DATA_PURCHASE_SUCCESS,
    DATA_PURCHASE_FAILED,

    // ── Admin / ops alerts ──────────────────────────────────────────────────
    ADMIN_PAYEELORD_LOW_BALANCE
}
