package com.moniewise.moniewise_backend.enums;

public enum TransactionType {
    DEPOSIT,
    WITHDRAWAL,
    TRANSFER,
    DISBURSEMENT,
    BUDGET_COMPLETION_REFUND,
    WALLET_DEPOSIT,
    WALLET_DEDUCTION,
    ENVELOPE_DISBURSEMENT,
    DISBURSEMENT_REFUNDED,
    BUDGET_UNALLOCATED_REFUNDED,
    BUDGET_ALLOCATION,
    BUDGET_EXTENSION,
    STRICT_LOCK_ROLLBACK,
    BUDGET_CREATION_FEE,
    ENVELOPE_TO_ENVELOPE,
    ENVELOPE_TO_EXTERNAL,
    ENVELOPE_DISBURSEMENT_PENDING,
    FAILED
}