package com.moniewise.moniewise_backend.enums;

public enum TransactionType {
    BUDGET_COMPLETION_REFUND,
    WALLET_DEPOSIT,
    WALLET_DEDUCTION,
    ENVELOPE_DISBURSEMENT,
    DISBURSEMENT_REFUNDED,
    BUDGET_UNALLOCATED_REFUNDED,
    BUDGET_ALLOCATION,
    BUDGET_EXTENSION,
    STRICT_LOCK_ROLLBACK,
    BUDGET_CREATION_FEE,
    ENVELOPE_TO_ENVELOPE,
    ENVELOPE_TO_EXTERNAL,
    FAILED,
    USER_TO_USER,
    WALLET_TO_BUDGET,
    WALLET_TO_EXTERNAL,
    WALLET_TO_USER,
    ENVELOPE_TO_USER,
    USER_TO_ENVELOPE,
    ROLLOVER_REFUND,
    WALLET_WITHDRAWAL,
    WALLET_WITHDRAWAL_FEE,
    SAVINGS_DEPOSIT

    }
