package com.moniewise.moniewise_backend.enums;

public enum TransactionType {
    DEPOSIT, WITHDRAWAL, TRANSFER, DISBURSEMENT, BUDGET_COMPLETION_REFUND,  WALLET_DEPOSIT,
    WALLET_DEDUCTION,
    ENVELOPE_DISBURSEMENT, DISBURSEMENT_REFUNDED
}